### ISSUE TITLE
Hotspot.create always throws error

### ISSUE THREAD

**Issue by luandro** [aboozaid/react-native-wifi-hotspot#11]
Tried running the example code for `Hotspot.create` but I get error every time. Is this functionality depended on the hardware, or should it work on any device?

**Comment by aboozaid** [comment]
What's your device OS Version?

**Comment by luandro** [comment]
`Hotspot.create` didn't work using Android 6.0.

Also tested on an Android 9.0, in which not even `Hotspot.enable` worked.

**Comment by aboozaid** [comment]
You can't change wifi hotspot without enabling it first. Also, check the modify system settings permission is set to on.

**Comment by aluno20182** [comment]
Hi, I have the same problem, i can't enable the hotspot even with all permissions set on.
any suggestion?

**Comment by aboozaid** [comment]
Till now the library doesn't support a workaround for android 8++, I will solve this in next updates

**Comment by aluno20182** [comment]
When this update will come out?
