### ISSUE TITLE
RN 0.61 issues

### ISSUE THREAD

**Issue by mvniekerk** [aboozaid/react-native-wifi-hotspot#14]
Hello -
I tried to compile the package in a React Native 0.61 project, following the instructions as per the Readme. I've found the following issues:

1. Uses rnpm - to be deprecated.
2. The rnpm directive of new HotspotModule() causes compiler errors.
3. Not using AndroidX but using AppCompat

**Comment by mvniekerk** [comment]
https://github.com/assemmohamedali/react-native-wifi-hotspot/pull/15 Makes it compile with 0.61

**Comment by aboozaid** [comment]
Added. I will push this into npm as well

**Comment by ShivamJoker** [comment]
I think we still have the RNPM issue it's not working with latest version of RN
