### ISSUE TITLE
react-native link react-native-wifi-hotspot do not work

### ISSUE THREAD

**Issue by ggunti** [aboozaid/react-native-wifi-hotspot#3]
I get the following error when run "react-native link react-native-wifi-hotspot"
![image](https://user-images.githubusercontent.com/26307699/46583049-4696fb00-ca59-11e8-887c-20bcd0c83209.png)

**Comment by ggunti** [comment]
My fault, it was just a typo

**Comment by aboozaid** [comment]
Never mind, Thanks for closing the issue.
