### ISSUE TITLE
Unable to find a matching configuration of project :react-native-wifi-hotspot

### ISSUE THREAD

**Issue by JasonBarbra** [aboozaid/react-native-wifi-hotspot#43]
react-native:  "^0.63.5"
buildToolsVersion = "28.0.3"
minSdkVersion = 21
compileSdkVersion = 28
targetSdkVersion = 28
gradle-6.0.1

Hey I did all configuration steps :

1. react-native link react-native-wifi-hotspot
2. include ':hotspotmanager'
project(':hotspotmanager').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wifi-hotspot/android/hotspotmanager')
3. adding packages in MainApplication.java 
          packages.add(new MainReactPackage());
          packages.add(new HotspotPackage());
But I always get build error  with text : Unable to find a matching configuration of project :react-native-wifi-hotspot

**Comment by aboozaid** [comment]
I don't recommend to use this module anymore. I will publish another one very soon please stay tuned!

**Comment by JasonBarbra** [comment]
Woow that sounds good :) the thing that is the most interesting for me is listing devices connected to hotspot, is this feature still will be available in new module ?

**Comment by aboozaid** [comment]
yes you will be able to get the IP addresses of the connected devices.

**Comment by JasonBarbra** [comment]
Hey @aboozaid when do you plan new release ? :)
