### ISSUE TITLE
Task :react-native-wifi-hotspot:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by savancodexive** [aboozaid/react-native-wifi-hotspot#44]
Version List

javac 11.0.18
Node : v18.14.0
ruby : 2.7.6p219
"react": "18.2.0"
"react-native": "0.71.4"

`> Task :react-native-wifi-hotspot:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
54 actionable tasks: 54 executed
/Users/csmac/Desktop/node_modules/react-native-wifi-hotspot/android/app/src/main/java/reactnative/hotspot/HotspotModule.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
Note: /Users/csmac/Desktop/node_modules/react-native-wifi-hotspot/android/app/src/main/java/reactnative/hotspot/HotspotManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-wifi-hotspot:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/csmac/Desktop/node_modules/react-native-wifi-hotspot/android/app/src/main/java/reactnative/hotspot/HotspotModule.java:4: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
Note: /Users/csmac/Desktop/node_modules/react-native-wifi-hotspot/android/app/src/main/java/reactnative/hotspot/HotspotManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-wifi-hotspot:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

    at makeError (/Users/csmac/Desktop/HostApp/node_modules/execa/index.js:174:9)
    at /Users/csmac/Desktop/HostApp/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/Users/csmac/Desktop/HostApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/csmac/Desktop/HostApp/node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by aboozaid** [comment]
this module is deprecated and I'm working on another one I will release it these days
