### ISSUE TITLE
example for file sharing

### ISSUE THREAD

**Issue by mfachmirizal** [aboozaid/react-native-wifi-hotspot#5]
Could you give us an example to use this library for file sharing over wifi?..

thanks..

**Comment by aboozaid** [comment]
I'm building a new module for that purpose with the help of this lib too.

**Comment by peckyboy** [comment]
Any luck with it? @assemmohamedali ? I'm in need of such a module

**Comment by aboozaid** [comment]
@peckyboy if you need a quick way to get started to this (until I release this module) you can use react-native-tcp and this lib to do that task. The idea is you just need to put the devices which they need to connect in a same network and then open a socket to send data over it.

**Comment by peckyboy** [comment]
Oh! I see. I actually looked at that module but wasn't very detailed so I thought it wasn't what I looking for. You're saying I'd have to create the hotspot manually and open a socket to send and receive data? @assemmohamedali

**Comment by aboozaid** [comment]
Yeah, exactly my lib will help you establish a hotspot and ask a device to connect to then use react-native-tcp to open a socket.

**Comment by peckyboy** [comment]
Awesome @assemmohamedali . Looking forward to it. Thanks for your responses
